language: android
android:
  components:
     # Update Android SDK Tools
    - tools

    - build-tools-25.0.1
    - android-25

    # Support library
    - extra-android-support
    - extra-android-m2repository