language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "ramonspain-github"
    token:
      secure: "538c6ed0a5eb4e4c046be86bad9ad9a55515bdbb"
jdk:
  - oraclejdk8
script:
  - ./gradlew sonarqube
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
